version: '3'
services:
    server:
      build: .
      command:
         python3 manage.py runserver 0.0.0.0:8000
      #useful in development to track the changes
      volumes:
        - ./TODOList:/code
      ports:
        - "8000:8000"
      env_file:
        - .env
